
globalVariables(
  c(
    'Location',
    'ID',
    'GPS',
    'Status',
    'Tree No',
    '.',
    'Descriptor',
    'Value',
    'Crown radius',
    'Tap test',
    'Canopy closure',
    'Symptom Type',
    'Size',
    'Count',
    'Crack size',
    'Active bleeds',
    'Average Crack Size',
    'Black staining',
    'Calloused wound',
    'Agrillus exit holes',
    'Crown mildew',
    'Crown density',
    'Dbh',
    'Lower Crown Ht',
    'Missing crown',
    'Timber Ht',
    'Total Ht',
    'Average Crown radius',
    'Average Bleed Size',
    'Black Staining Size',
    'Calloused Wound Size',
    'Symptomatic',
    'Active Bleed Size',
    'Average Black Staining Size',
    'Average Calloused Wound Size',
    'Direction',
    'Crack No',
    'Average Active Bleed Size',
    'V1',
    'V2',
    'Dimension 1',
    'Dimension 2',
    'Feature',
    'Gini Importance',
    'Sample2',
    'Sample1',
    'Proximity',
    'PHI',
    'Class',
    'Margin',
    'Mean',
    'Correction'
  )
)
