---
title: Figures
output: 
  pdf_document:
    keep_tex: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r decline_index_plot,fig.cap='Decline indexes for all 174 trees. The chosen group categories were selected in the field prior to data collection. AOD = acute oak decline; COD = chronic oak decline. Remisson tress were those that were known to have had active bleeds within the previous 3 years.'}
loadd(decline_indexes_plot)

decline_indexes_plot
```

```{r descriptor_contributions, fig.height = 6,fig.cap = 'Descriptor importance scores from random forest models for relative contributions to\ndecline index measures.'}
loadd(descriptor_contribution_plots)

descriptor_contribution_plots$a + descriptor_contribution_plots$b
```

```{r PDI_response_surfaces,fig.height = 6,fig.cap='PDI response surfaces for simulated descriptor values from trained random forest models.'}
loadd(PDI_response_surfaces)

grid.arrange(PDI_response_surfaces[[1]],
             PDI_response_surfaces[[2]],
             PDI_response_surfaces[[3]],
             PDI_response_surfaces$legend,
             nrow = 2,newpage = F)
```


```{r DAI_response_surfaces,fig.height = 8,fig.cap='DAI response surfaces for simulated descriptor values from trained random forest models.'}
loadd(DAI_response_surfaces)

grid.arrange(textGrob(expression(bold('AOD')),hjust = -0.1),
             textGrob(expression(bold('COD')),hjust = -0.1),
             textGrob(expression(bold('Neutral')),rot = 90,hjust = -0.1),
             textGrob(expression(bold('Moderate')),rot = 90,hjust = -0.1),
             textGrob(expression(bold('Severe')),rot = 90,hjust = -0.1),
             DAI_response_surfaces$`a)`,
             DAI_response_surfaces$`b)`,
             DAI_response_surfaces$`c)`,
             DAI_response_surfaces$`d)`,
             DAI_response_surfaces$`e)`,
             DAI_response_surfaces$`f)`,
             DAI_response_surfaces$legend,
             ncol = 4,
             layout_matrix = rbind(c(NA,1,2,NA),c(3,6,9,12),c(4,7,10,12),c(5,8,11,12)),
             widths = c(1,10,10,2),
             heights = c(1,10,10,10),
             newpage = F)
```

```{r DI_space,fig.cap='Two dimensional continuum of the phenotypic decline indexes for oak decline severity. Decline category boundaries intended as a guide to aid interpretation only. Grey area indicates area for which the decline indexes are currently undefined.' ,fig.height=3,fig.width=5}
DIspace()
```