---
title: Supplementary information
output: 
  pdf_document:
    keep_tex: false
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r phenotypic_descriptors,cache=FALSE}
loadd(phenotypic_descriptor_info)

phenotypic_descriptor_info %>%
  select(-`Descriptor Type`,-`Data Type`) %>%
  kable(format = 'latex',
        booktabs = TRUE,
        longtable = TRUE,
        caption = 'Phenotypic descriptors collected for oak decline severity.') %>%
  kable_styling(latex_options = c('striped','repeat_header'),repeat_header_continued = TRUE) %>%
  # column_spec(1,width = '1.5cm') %>%
  column_spec(1,width = '3cm') %>%
  column_spec(2:3,width = '6cm') #%>%
  # collapse_rows(columns = 1,latex_hline = "major", valign = "middle")
```

```{r descriptor_adjustment,fig.cap='Exapmle of overall mean adjustment applied to the diameter at breast height (m) descriptor. Error bars show ±1SE of the mean. Dashed red line shows the overall mean.'}
loadd(descriptor_adjustment_example)

descriptor_adjustment_example %>%
  wrap_plots()
```

```{r descriptor_adjustment_factors}
loadd(site_correction_factors)

site_correction_factors %>%
  rename(Adjustment = Correction) %>%
  mutate_if(is.double,signif,digits = 3) %>%
  kable(format = 'latex',booktabs = TRUE,caption = 'Descriptor adjustment factors at each site.') %>%
  collapse_rows(columns = 1,latex_hline = "major", valign = "middle")
```

```{r modelTuningResultsPlot,fig.cap='Random forest parameter tuning results for decline index models.'}
loadd(rf_tune_plot)

rf_tune_plot
```

```{r site_differences,fig.cap='Differences between sites in phenotypic descriptors analysed by supervised random forest classification. a) Multidimensional scaling (MDS) scatter plot of random forest proximity values of individual trees scaled to two dimensions. b) Descriptor mean decrease in accuracy importances measures. Descriptors ordered in descending importance.',fig.height=6}
loadd(site_differences_mds_plot)
grid.arrange(site_differences_mds_plot$a,site_differences_mds_plot$b,nrow = 1)
```

```{r site_differences_corrected,fig.cap='Differences between sites in phenotypic descriptors after adjustment of tree size descriptors analysed by supervised random forest classification. a) Multidimensional scaling (MDS) scatter plot of random forest proximity values of individual trees scaled to two dimensions. b) Descriptor mean decrease in accuracy importances measures. Descriptors ordered in descending importance.',fig.height=6}
loadd(site_differences_post_correction_mds_plot)
grid.arrange(site_differences_post_correction_mds_plot$a,site_differences_post_correction_mds_plot$b,nrow = 1)
```

```{r PDInumeric,fig.height=9,fig.cap='Continuous descriptors plotted against the PDI.'}
loadd(descriptor_scatter_plots)

descriptor_scatter_plots$PDI_numeric
```

```{r PDIfactor,fig.height=8,fig.cap='Categorical descriptors plotted against the PDI.'}
descriptor_scatter_plots$PDI_factor
```

```{r DAInumeric,fig.height=9,fig.cap='Continuous descriptors plotted against the DAI.'}
descriptor_scatter_plots$DAI_numeric
```

```{r DAIfactor,fig.height=8,fig.cap='Categorical descriptors plotted against the DAI.'}
descriptor_scatter_plots$DAI_factor
```
