---
output: 
  pdf_document:
    keep_tex: false
header-includes:
  - \newcommand{\beginsupplement}{\setcounter{table}{0}  \renewcommand{\thetable}{S\arabic{table}} \setcounter{figure}{0} \renewcommand{\thefigure}{S\arabic{figure}}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

\beginsupplement

```{r descriptor_adjustment,fig.cap='Exapmle of overall mean adjustment applied to the diameter at breast height (m) descriptor. Error bars show ±1SE of the mean. Dashed red line shows the overall mean.'}
loadd(descriptor_adjustment_example)

descriptor_adjustment_example %>%
  wrap_plots()
```

```{r modelTuningResultsPlot,fig.cap='Random forest parameter tuning results for decline index models.'}
loadd(rf_tune_plot)

rf_tune_plot
```

```{r site_differences,fig.cap='Differences between sites in phenotypic descriptors analysed by supervised random forest classification. a) Multidimensional scaling (MDS) scatter plot of random forest proximity values of individual trees scaled to two dimensions. b) Descriptor mean decrease in accuracy importances measures. Descriptors ordered in descending importance.',fig.height=6}
loadd(site_differences_mds_plot)
grid.arrange(site_differences_mds_plot$a,site_differences_mds_plot$b,nrow = 1)
```

```{r site_differences_corrected,fig.cap='Differences between sites in phenotypic descriptors after adjustment of tree size descriptors analysed by supervised random forest classification. a) Multidimensional scaling (MDS) scatter plot of random forest proximity values of individual trees scaled to two dimensions. b) Descriptor mean decrease in accuracy importances measures. Descriptors ordered in descending importance.',fig.height=6}
loadd(site_differences_post_adjustment_mds_plot)
grid.arrange(site_differences_post_adjustment_mds_plot$a,site_differences_post_adjustment_mds_plot$b,nrow = 1)
```

```{r PDInumeric,fig.height=9,fig.cap='Continuous descriptors plotted against the PDI.'}
loadd(descriptor_scatter_plots)

descriptor_scatter_plots$PDI_numeric
```

```{r PDIfactor,fig.height=9,fig.cap='PDI box plots of the categorical descriptors.'}
descriptor_scatter_plots$PDI_factor
```

```{r DAInumeric,fig.height=9,fig.cap='Continuous descriptors plotted against the DAI.'}
descriptor_scatter_plots$DAI_numeric
```

```{r DAIfactor,fig.height=9,fig.cap='DAI box plots of the categorical descriptors.'}
descriptor_scatter_plots$DAI_factor
```
