---
title: Tables
output: 
  pdf_document:
    includes:
header-includes:
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r PDI_lime_results}
loadd(PDI_lime_analysis_table)

PDI_lime_analysis_table %>%
  kable(format = 'latex',
        booktabs = TRUE,
        escape = FALSE,
        caption = 'LIME results for oak decline severity cases in the PDI index model $M_{PDI}$. Top four important descriptors show. Descriptors ordered by descending absolute weight within each case.') %>%
  collapse_rows(columns = 1:3, latex_hline = "major", valign = "middle")
```

```{r DAI_lime_results}
loadd(DAI_lime_analysis_table)

DAI_lime_analysis_table %>%
  kable(format = 'latex',
        booktabs = TRUE,
        escape = FALSE,
        caption = 'LIME results of oak decline type and severity in the DAI index model $M_{DAI}$. Top four important descriptors shown. Descriptors ordered by descending absolute weight within each case.') %>%
  column_spec(5,width = '4cm') %>%
  collapse_rows(columns = 1:4, latex_hline = "custom", valign = "middle",custom_latex_hline = 1:4)
```

